### PR TITLE
Add harmonization method plugin infrastructure

### LINKED ISSUE #23: Improve process for registering new harmonization techniques
Currently, new harmonization classes must be placed in the `harmonization` directory of `habet`. It would be nice if these techniques could be registered without needing to place them in a specific directory.

Probably depends on #22, as I know there's some kind of entry point / plugin infrastructure with `setup.py`, but I'm not familiar with it.

### PR DESCRIPTION
**Pull request by tao558**
Closes #23

### CODE REVIEW

**Review by ebrahimebrahim — APPROVED** [review]
This is great! I haven't tested it but I watched you demonstrate it working, so I am happy with merging this.

We might consider creating a minimal example plugin, and/or adding some text to the readme that describes the steps of creating a plugin.

**Comment by tao558** [comment]
> We might consider creating a minimal example plugin, and/or adding some text to the readme that describes the steps of creating a plugin.

I agree. I'll create some issues and merge?

**Comment by ebrahimebrahim** [comment]
> I agree. I'll create some issues and merge?

Sounds good!

**Comment by tao558** [comment]
> We might consider creating a minimal example plugin, and/or adding some text to the readme that describes the steps of creating a plugin.

See #29 and #28

**Pull request merged**
